language: ruby
rvm:
  - 2.1.2
before_script:
  # - mysql -e 'create database pop_test;'
  # - "echo 'test:\n username: travis\n encoding: utf8\n database: pop_test\n adapter: mysql2' > config/database.yml"
  # - bundle exec rake db:schema:load
script:
  - bundle exec rspec spec
after_failure:
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
  - "echo $RAILS_ENV"
  - "bundle exec rake --version"
